### ISSUE TITLE
animation freezes during play in some players

### ISSUE THREAD

**Issue by sarahcd** [bohrer-lab/ecodata-matlab#113]
**Describe the bug**
See emails from Feb 2024. There is some kind of encoding/file issue: in QuickTime and on my PowerPoint, the animation freezes at 29 Oct 2020 and then after many seconds starts moving again in mid-May 2021. In VLC viewer, it looks great.

**Additional context**
Email response: I have seen issues like this with other animations in various media players (Quicktime, Windows media player), while they seem to be fine in VLC player. My best guess is that it’s some sort of encoding incompatibility with the other media players. I’m pretty sure VLC player also uses ffmpeg under the hood. I’ll experiment with the encoding settings and see if I can find an option that will work better with other video players.

**Comment by jemissik** [comment]
This has been fixed in ecodata-prepare; it will be in the next release
see https://github.com/jemissik/ecodata/pull/164

**Comment by jemissik** [comment]
This is fixed in [ecodata 0.2.7](https://github.com/jemissik/ecodata/releases/tag/v0.2.7)
